package com.stores.app.storesecond.entities;
// Generated 28 nov. 2016 13:45:51 by Hibernate Tools 5.2.0.Beta1

//import java.util.HashSet;
//import java.util.Set;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Colours generated by hbm2java
 */
public class Colours /*implements java.io.Serializable*/ 
{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idColours;
	@Column
	private String nameColours;
	//private Set itemses = new HashSet(0);

	public Colours() 
	{
	}

	public Colours(int idColours) 
	{
		this.idColours = idColours;
	}

	public Colours(int idColours, String nameColours/*, Set itemses*/) 
	{
		this.idColours = idColours;
		this.nameColours = nameColours;
		//this.itemses = itemses;
	}

	public int getIdColours() 
	{
		return this.idColours;
	}

	public void setIdColours(int idColours)
	{
		this.idColours = idColours;
	}

	public String getNameColours()
	{
		return this.nameColours;
	}

	public void setNameColours(String nameColours) 
	{
		this.nameColours = nameColours;
	}

	/*public Set getItemses() {
		return this.itemses;
	}

	public void setItemses(Set itemses) {
		this.itemses = itemses;
	}*/

}
