package com.stores.app.storesecond.entities;
// Generated 28 nov. 2016 13:45:51 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Items generated by hbm2java
 */
public class Items /*implements java.io.Serializable*/
{

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idItems;
	@OneToOne
	private Brands brands;
	@OneToOne
	private Colours colours;
	@Column
	private String nameItems;
	@Column
	private String descriptionItems;
	@Column
	private String linkItems;

	public Items(){
	}

	public Items(int idItems, Brands brands, Colours colours)
	{
		this.idItems = idItems;
		this.brands = brands;
		this.colours = colours;
	}

	public Items(int idItems, Brands brands, Colours colours, String nameItems, String descriptionItems,
			String linkItems)
	{
		this.idItems = idItems;
		this.brands = brands;
		this.colours = colours;
		this.nameItems = nameItems;
		this.descriptionItems = descriptionItems;
		this.linkItems = linkItems;
	}

	public int getIdItems()
	{
		return this.idItems;
	}

	public void setIdItems(int idItems)
	{
		this.idItems = idItems;
	}

	public Brands getBrands() 
	{
		return this.brands;
	}

	public void setBrands(Brands brands) 
	{
		this.brands = brands;
	}

	public Colours getColours()
	{
		return this.colours;
	}

	public void setColours(Colours colours)
	{
		this.colours = colours;
	}

	public String getNameItems() 
	{
		return this.nameItems;
	}

	public void setNameItems(String nameItems)
	{
		this.nameItems = nameItems;
	}

	public String getDescriptionItems() 
	{
		return this.descriptionItems;
	}

	public void setDescriptionItems(String descriptionItems) 
	{
		this.descriptionItems = descriptionItems;
	}

	public String getLinkItems() 
	{
		return this.linkItems;
	}

	public void setLinkItems(String linkItems) 
	{
		this.linkItems = linkItems;
	}

}
