package com.stores.app.storesecond.model;
// Generated 6 janv. 2017 01:35:15 by Hibernate Tools 5.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Brand generated by hbm2java
 */
public class Brand  implements java.io.Serializable {


     private int idBrand;
     private String nameBrand;
     private Set items = new HashSet(0);

    public Brand() {
    }

	
    public Brand(int idBrand) {
        this.idBrand = idBrand;
    }
    public Brand(int idBrand, String nameBrand, Set items) {
       this.idBrand = idBrand;
       this.nameBrand = nameBrand;
       this.items = items;
    }
   
    public int getIdBrand() {
        return this.idBrand;
    }
    
    public void setIdBrand(int idBrand) {
        this.idBrand = idBrand;
    }
    public String getNameBrand() {
        return this.nameBrand;
    }
    
    public void setNameBrand(String nameBrand) {
        this.nameBrand = nameBrand;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


