package com.stores.app.storesecond.model;
// Generated 4 janv. 2017 23:30:32 by Hibernate Tools 5.2.0.CR1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "Brand")
public class Brand /*implements java.io.Serializable*/ {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int idBrand;
  @Column
  private String nameBrand;
  //private Set items = new HashSet(0);

  public Brand() {
  }

  public Brand(int idBrand) {
    this.idBrand = idBrand;
  }

  public Brand(int idBrand, String nameBrand/*, Set items*/) {
    this.idBrand = idBrand;
    this.nameBrand = nameBrand;
    //this.items = items;
  }

  public int getIdBrand() {
    return this.idBrand;
  }

  public void setIdBrand(int idBrand) {
    this.idBrand = idBrand;
  }

  public String getNameBrand() {
    return this.nameBrand;
  }

  public void setNameBrand(String nameBrand) {
    this.nameBrand = nameBrand;
  }

 /* public Set getItems() {
    return this.items;
  }

  public void setItems(Set items) {
    this.items = items;
  }*/

}
