package com.stores.app.storesecond.model;
// Generated 4 janv. 2017 23:30:32 by Hibernate Tools 5.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category")
public class Category /*implements java.io.Serializable*/ {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)

  private int idCategory;
  @Column
  private String nameCategory;
  //private Set items = new HashSet(0);

  public Category() {
  }

  public Category(int idCategory) {
    this.idCategory = idCategory;
  }

  public Category(int idCategory, String nameCategory/*, Set items*/) {
    this.idCategory = idCategory;
    this.nameCategory = nameCategory;
    //this.items = items;
  }

  public int getIdCategory() {
    return this.idCategory;
  }

  public void setIdCategory(int idCategory) {
    this.idCategory = idCategory;
  }

  public String getNameCategory() {
    return this.nameCategory;
  }

  public void setNameCategory(String nameCategory) {
    this.nameCategory = nameCategory;
  }

  /*public Set getItems() {
    return this.items;
  }

  public void setItems(Set items) {
    this.items = items;
  }*/

}
