package com.stores.app.storesecond.model;
// Generated 6 janv. 2017 01:35:15 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

  private int idCategory;
  private String nameCategory;
  private Set items = new HashSet(0);

  public Category() {
  }

  public Category(int idCategory) {
    this.idCategory = idCategory;
  }

  public Category(int idCategory, String nameCategory, Set items) {
    this.idCategory = idCategory;
    this.nameCategory = nameCategory;
    this.items = items;
  }

  public int getIdCategory() {
    return this.idCategory;
  }

  public void setIdCategory(int idCategory) {
    this.idCategory = idCategory;
  }

  public String getNameCategory() {
    return this.nameCategory;
  }

  public void setNameCategory(String nameCategory) {
    this.nameCategory = nameCategory;
  }

  public Set getItems() {
    return this.items;
  }

  public void setItems(Set items) {
    this.items = items;
  }

}
