package com.stores.app.storesecond.model;
// Generated 4 janv. 2017 23:30:32 by Hibernate Tools 5.2.0.CR1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Colour generated by hbm2java
 */
@Entity
@Table(name="Colour")
public class Colour /*implements java.io.Serializable*/ {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int idColour;
  @Column
  private String nameColour;
  @Column
  private String valueColour;
  //private Set items = new HashSet(0);

  public Colour() {
  }

  public Colour(int idColour) {
    this.idColour = idColour;
  }

  public Colour(int idColour, String nameColour, String valueColour/*,
      Set items*/) {
    this.idColour = idColour;
    this.nameColour = nameColour;
    this.valueColour = valueColour;
   // this.items = items;
  }

  public int getIdColour() {
    return this.idColour;
  }

  public void setIdColour(int idColour) {
    this.idColour = idColour;
  }

  public String getNameColour() {
    return this.nameColour;
  }

  public void setNameColour(String nameColour) {
    this.nameColour = nameColour;
  }

  public String getValueColour() {
    return this.valueColour;
  }

  public void setValueColour(String valueColour) {
    this.valueColour = valueColour;
  }

  /*public Set getItems() {
    return this.items;
  }

  public void setItems(Set items) {
    this.items = items;
  }*/

}
