package com.stores.app.storesecond.model;
// Generated 6 janv. 2017 01:35:15 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Colour generated by hbm2java
 */
public class Colour implements java.io.Serializable {

  private int idColour;
  private String nameColour;
  private String valueColour;
  private Set items = new HashSet(0);

  public Colour() {
  }

  public Colour(int idColour) {
    this.idColour = idColour;
  }

  public Colour(int idColour, String nameColour, String valueColour,
      Set items) {
    this.idColour = idColour;
    this.nameColour = nameColour;
    this.valueColour = valueColour;
    this.items = items;
  }

  public int getIdColour() {
    return this.idColour;
  }

  public void setIdColour(int idColour) {
    this.idColour = idColour;
  }

  public String getNameColour() {
    return this.nameColour;
  }

  public void setNameColour(String nameColour) {
    this.nameColour = nameColour;
  }

  public String getValueColour() {
    return this.valueColour;
  }

  public void setValueColour(String valueColour) {
    this.valueColour = valueColour;
  }

  public Set getItems() {
    return this.items;
  }

  public void setItems(Set items) {
    this.items = items;
  }

}
