package com.stores.app.storesecond.model;
// Generated 4 janv. 2017 23:30:32 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="Item")
public class Item /*implements java.io.Serializable*/ {
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private int idItem;
  @OneToOne
  private Brand brand;
  @OneToOne
  private Category category;
  @OneToOne
  private Colour colour;
  @Column
  private String nameItem;
  @Column
  private String descriptionItem;
  @Column
  private String linkItem;

  public Item() {
  }

  public Item(int idItem, Brand brand, Category category, Colour colour) {
    this.idItem = idItem;
    this.brand = brand;
    this.category = category;
    this.colour = colour;
  }

  public Item(int idItem, Brand brand, Category category, Colour colour,
      String nameItem, String descriptionItem, String linkItem) {
    this.idItem = idItem;
    this.brand = brand;
    this.category = category;
    this.colour = colour;
    this.nameItem = nameItem;
    this.descriptionItem = descriptionItem;
    this.linkItem = linkItem;
  }

  public int getIdItem() {
    return this.idItem;
  }

  public void setIdItem(int idItem) {
    this.idItem = idItem;
  }

  public Brand getBrand() {
    return this.brand;
  }

  public void setBrand(Brand brand) {
    this.brand = brand;
  }

  public Category getCategory() {
    return this.category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }

  public Colour getColour() {
    return this.colour;
  }

  public void setColour(Colour colour) {
    this.colour = colour;
  }

  public String getNameItem() {
    return this.nameItem;
  }

  public void setNameItem(String nameItem) {
    this.nameItem = nameItem;
  }

  public String getDescriptionItem() {
    return this.descriptionItem;
  }

  public void setDescriptionItem(String descriptionItem) {
    this.descriptionItem = descriptionItem;
  }

  public String getLinkItem() {
    return this.linkItem;
  }

  public void setLinkItem(String linkItem) {
    this.linkItem = linkItem;
  }

}
