package com.stores.app.storesecond.model;
// Generated 6 janv. 2017 01:35:15 by Hibernate Tools 5.2.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

  private int idUser;
  private String userName;
  private String userLastName;
  private String userEmail;
  private String userPassword;
  private String userSecurityQuestion1;
  private String userSecurityQuestion2;

  public User() {
  }

  public User(int idUser) {
    this.idUser = idUser;
  }

  public User(int idUser, String userName, String userLastName,
      String userEmail, String userPassword, String userSecurityQuestion1,
      String userSecurityQuestion2) {
    this.idUser = idUser;
    this.userName = userName;
    this.userLastName = userLastName;
    this.userEmail = userEmail;
    this.userPassword = userPassword;
    this.userSecurityQuestion1 = userSecurityQuestion1;
    this.userSecurityQuestion2 = userSecurityQuestion2;
  }

  public int getIdUser() {
    return this.idUser;
  }

  public void setIdUser(int idUser) {
    this.idUser = idUser;
  }

  public String getUserName() {
    return this.userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public String getUserLastName() {
    return this.userLastName;
  }

  public void setUserLastName(String userLastName) {
    this.userLastName = userLastName;
  }

  public String getUserEmail() {
    return this.userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public String getUserPassword() {
    return this.userPassword;
  }

  public void setUserPassword(String userPassword) {
    this.userPassword = userPassword;
  }

  public String getUserSecurityQuestion1() {
    return this.userSecurityQuestion1;
  }

  public void setUserSecurityQuestion1(String userSecurityQuestion1) {
    this.userSecurityQuestion1 = userSecurityQuestion1;
  }

  public String getUserSecurityQuestion2() {
    return this.userSecurityQuestion2;
  }

  public void setUserSecurityQuestion2(String userSecurityQuestion2) {
    this.userSecurityQuestion2 = userSecurityQuestion2;
  }

}
